### ISSUE TITLE
I have the following error 

### ISSUE THREAD

**Issue by simona2017** [vicalloy/django-lb-workflow#11]
Hi, 

I have the following error. I'm not sure what I did wrong. Do you mind helping me out?

Thanks,

<img width="938" alt="screen shot 2018-06-07 at 6 00 26 pm" src="https://user-images.githubusercontent.com/22427968/41128613-d0835c9c-6a7c-11e8-97ba-05a7cb072b6e.png">

**Comment by vicalloy** [comment]
fixed

**Comment by simona2017** [comment]
Thank you so much. It worked great. Now I am getting a ccs error. 
<img width="1259" alt="screen shot 2018-06-08 at 6 01 13 am" src="https://user-images.githubusercontent.com/22427968/41152433-90faa804-6ae1-11e8-991e-2ca2416a26ef.png">

**Comment by vicalloy** [comment]
The test project use bower to manage static resource(js/css).
Use `python testproject/manage.py bower_install` to download js&css.
The settings is in `lbworkflow/tests/settings.py`(find bower)

You can visit `https://github.com/nvbn/django-bower` to get more about `django bower`.

**Comment by simona2017** [comment]
I did all of the above and I'm still getting the same error. Is there a way to download those files manually and not through bower?

**Comment by vicalloy** [comment]
did `python testproject/manage.py bower_install` success?
You should find all js/css in folder `lbworkflow/bower_components/`.
BOWER_COMPONENTS_ROOT should be `lbworkflow/`, but the settings seems missing.

no easy way to download all those files without bower.
You can download js/css manually with bower.
`bower install admin-lte#2.3.11`
You can should install all lib in `lbworkflow/tests/settings.py BOWER_INSTALLED_APPS`

**Comment by simona2017** [comment]
Thank you so much it worked. The system showed I had install bower before but it wasn't showing in the folder, I had to install Node and npm, then run the command line for bower_installed and now it works perfectly. Thank you so much!
